<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos [
        <!ELEMENT datos ((equipos | usuarios | prestamos)*)>

        <!ELEMENT usuarios (u_nombre, departamento+, telefono+, correo+, ubicacion+)>
        <!ELEMENT u_nombre (#PCDATA)>
        <!ELEMENT departamento (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT correo (#PCDATA)>
        <!ELEMENT ubicacion (#PCDATA)>
        <!ATTLIST usuarios id ID #REQUIRED>

        <!ELEMENT equipos (tipo, marca?, uso?, SO, Hardware, Software)>
        <!ELEMENT tipo (#PCDATA)>
        <!ELEMENT marca (#PCDATA)>
        <!ELEMENT uso (#PCDATA)>
        <!ELEMENT SO (Nombre_SO, version)>
        <!ELEMENT Nombre_SO (#PCDATA)>
        <!ELEMENT version (#PCDATA)>
        <!ELEMENT Hardware (Procesador?, Cant_Memoria?, Disco, Pantalla?)>
        <!ELEMENT Procesador (#PCDATA)>
        <!ELEMENT Cant_Memoria (Velocidad)>
        <!ELEMENT Velocidad (#PCDATA)>
        <!ELEMENT Disco (Tipo_disc, Capacidad_disc)>
        <!ELEMENT Tipo_disc (#PCDATA)>
        <!ELEMENT Capacidad_disc (#PCDATA)>
        <!ELEMENT Pantalla (Diagonal, resolucion)>
        <!ELEMENT Diagonal (#PCDATA)>
        <!ELEMENT resolucion (#PCDATA)>
        <!ELEMENT Software (Licencia_Pago | Licencia_Libre)>
        <!ELEMENT Licencia_Pago (S_Nombre, S_Version?, S_Tipo?)>
        <!ELEMENT S_Nombre (#PCDATA)>
        <!ELEMENT S_Version (#PCDATA)>
        <!ELEMENT S_Tipo (#PCDATA)>
        <!ELEMENT Licencia_Libre (S_Nombre, S_Version?)>
        <!ATTLIST equipos id ID #REQUIRED>

        <!ELEMENT prestamos (F_Ini, F_Fin, F_Real_Devol?, Comentarios?)>
        <!ELEMENT F_Ini (#PCDATA)>
        <!ELEMENT F_Fin (#PCDATA)>
        <!ELEMENT F_Real_Devol (#PCDATA)>
        <!ELEMENT Comentarios (#PCDATA)>
        <!ATTLIST prestamos id ID #REQUIRED>
        <!ATTLIST prestamos U_id IDREF #REQUIRED>
        <!ATTLIST prestamos E_id IDREF #REQUIRED>
        ]>

<datos>
    <usuarios id="MC">
        <u_nombre>Mario Castro</u_nombre>
        <departamento>Desarrollo</departamento>
        <telefono>673429548</telefono>
        <correo>mariocastro@hotmail.com</correo>
        <ubicacion>Ramiro 21</ubicacion>
    </usuarios>

    <usuarios id="MK">
        <u_nombre>Milan Kundera</u_nombre>
        <departamento>Análisis</departamento>
        <telefono>634829540</telefono>
        <correo>milankun@gmail.com</correo>
        <ubicacion>Leganés 72</ubicacion>
    </usuarios>

    <equipos id="B">
        <tipo>Portatil</tipo>
        <SO>
            <Nombre_SO>Linux</Nombre_SO>
            <version>5.15.3</version>
        </SO>
        <Hardware>
            <Disco>
                <Tipo_disc>SSD</Tipo_disc>
                <Capacidad_disc>500GB</Capacidad_disc>
            </Disco>
        </Hardware>
        <Software>
            <Licencia_Pago>
                <S_Nombre>Apache</S_Nombre>
            </Licencia_Pago>
        </Software>
    </equipos>

    <equipos id="A">
        <tipo>Sobremesa</tipo>
        <SO>
            <Nombre_SO>Windows10</Nombre_SO>
            <version>1.3</version>
        </SO>
        <Hardware>
            <Disco>
                <Tipo_disc>SSD</Tipo_disc>
                <Capacidad_disc>1TB</Capacidad_disc>
            </Disco>
        </Hardware>
        <Software>
            <Licencia_Libre>
                <S_Nombre>LGPL</S_Nombre>
            </Licencia_Libre>
        </Software>
    </equipos>

    <prestamos id="PA" U_id="MC" E_id="A">
        <F_Ini>22/03/2021</F_Ini>
        <F_Fin>22/12/2021</F_Fin>
    </prestamos>

    <prestamos id="PB" U_id="MK" E_id="B">
        <F_Ini>19/03/2021</F_Ini>
        <F_Fin>19/10/2021</F_Fin>
    </prestamos>
</datos>
